input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
