server:
  port: 8083

spring:
  application:
    name: investment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/investment_db
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: investment-service-group
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/