server:
  port: 8084

spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

ml:
  base-url: http://localhost:8000

resilience4j:

  circuitbreaker:
    instances:
      paymentServiceCB:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      paymentServiceRetry:
        maxAttempts: 2
        waitDuration: 200ms

  timelimiter:
    instances:
      paymentServiceTimeout:
        timeoutDuration: 500ms

  bulkhead:
    instances:
      paymentServiceBulkhead:
        maxConcurrentCalls: 10