server:
  port: 8085

spring:
  application:
    name: payment-intent-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_intent_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    enable:
      all: true

resilience4j:

  circuitbreaker:
    instances:
      fraudServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 300ms
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  retry:
    instances:
      fraudServiceRetry:
        maxAttempts: 2
        waitDuration: 200ms

  timelimiter:
    instances:
      fraudServiceTimeout:
        timeoutDuration: 500ms

  bulkhead:
    instances:
      fraudServiceBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 0